package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"github.com/badaccuracyid/tpa-web-ef/internal/service"

	"github.com/badaccuracyid/tpa-web-ef/internal/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	authService := service.NewAuthService(ctx, r.DB)
	return authService.Register(&input)
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, oldPassword string, newPassword string) (*model.User, error) {
	authService := service.NewAuthService(ctx, r.DB)
	return authService.ChangePassword(oldPassword, newPassword)
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input model.LoginInput) (*model.User, error) {
	authService := service.NewAuthService(ctx, r.DB)
	return authService.Login(&input)
}
