// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}
